import bh1 from "@/public/collection/bombay-history/1.jpg"
import bh2 from "@/public/collection/bombay-history/2.jpg"
import bh3 from "@/public/collection/bombay-history/3.jpg"
import bh4 from "@/public/collection/bombay-history/4.jpg"
import bh5 from "@/public/collection/bombay-history/5.jpg"
import bh6 from "@/public/collection/bombay-history/6.jpg"
import bh7 from "@/public/collection/bombay-history/7.jpg"
import bh8 from "@/public/collection/bombay-history/8.jpg"
import bh9 from "@/public/collection/bombay-history/9.jpg"
import bh10 from "@/public/collection/bombay-history/10.jpg"
import bh11 from "@/public/collection/bombay-history/11.jpg"
import bh12 from "@/public/collection/bombay-history/12.jpg"
import bh13 from "@/public/collection/bombay-history/13.jpg"
import bh14 from "@/public/collection/bombay-history/14.jpg"
import bh15 from "@/public/collection/bombay-history/15.jpg"
import bh16 from "@/public/collection/bombay-history/16.jpg"
import bh17 from "@/public/collection/bombay-history/17.jpg"
import bh18 from "@/public/collection/bombay-history/18.jpg"
import bh19 from "@/public/collection/bombay-history/19.jpg"
import bh20 from "@/public/collection/bombay-history/20.jpg"

import popbh1 from "@/public/collection/bombay-history/popups/pop18.jpg"
import popbh2 from "@/public/collection/bombay-history/popups/pop01.jpg"
import popbh3 from "@/public/collection/bombay-history/popups/pop06.jpg"
import popbh4 from "@/public/collection/bombay-history/popups/pop04.jpg"
import popbh5 from "@/public/collection/bombay-history/popups/pop05.jpg"
import popbh6 from "@/public/collection/bombay-history/popups/pop08.jpg"
import popbh7 from "@/public/collection/bombay-history/popups/pop12.jpg"
import popbh8 from "@/public/collection/bombay-history/popups/pop11.jpg"
import popbh9 from "@/public/collection/bombay-history/popups/pop09.jpg"
import popbh10 from "@/public/collection/bombay-history/popups/pop03.jpg"
import popbh11 from "@/public/collection/bombay-history/popups/pop17.jpg"
import popbh12 from "@/public/collection/bombay-history/popups/pop10.jpg"
import popbh13 from "@/public/collection/bombay-history/popups/pop02.jpg"
import popbh14 from "@/public/collection/bombay-history/popups/pop20.jpg"
import popbh15 from "@/public/collection/bombay-history/popups/pop14.jpg"
import popbh16 from "@/public/collection/bombay-history/popups/pop15.jpg"
import popbh17 from "@/public/collection/bombay-history/popups/pop19.jpg"
import popbh18 from "@/public/collection/bombay-history/popups/pop07.jpg"
import popbh19 from "@/public/collection/bombay-history/popups/pop13.jpg"
import popbh20 from "@/public/collection/bombay-history/popups/pop16.jpg"

export const bombayHistory = [
    {img: bh1.src, name: "Elephanta Elephant", date: "c. 5th century CE\nStone", popupimg: popbh1.src, details:"The island of Elephanta derives its name from this stone elephant which was placed the entrance of the rock cut caves, dated to c. 5th – 6th centuries A.D. This stone elephant broke into several pieces when the English tried to remove it from the Island in order to ship it to England. The pieces were brought to the museum where it was reassembled by Dr. George Birdwood (former Curator of the Museum) and has since been displayed at the entrance of the Museum." },
    {img: bh2.src, name: "Heptanesia, (before 1600 CE)", date: "1913-14\nRelief map", popupimg: popbh2.src, details: "This 3 dimensional map of the original seven islands of Mumbai is titled Heptanesia, Greek for seven islands, which is the earliest documented name for the city recorded in the writings of Ptolemy. The Kamalnayan Bajaj Mumbai Gallery showcases Mumbai’s origins as a group of islands separated by swamps, marshland and mangroves, covered with coconut groves, and its development into a vibrant and elegant 19th century city."},
    {img: bh3.src, name: "Facsimile of Grose's Plan of Bombay, 1750", date: "1909-18\nWatercolour & ink on paper", popupimg: popbh3.src, details: "John Henry Grose was a writer and a covenanted servant of the East India Company. He came to Mumbai (Bombay) in the year 1750 in one of the East Indiamen and published his account “Voyages to the East Indies” in two parts in 1772. His plan is invaluable as every street within the walls of the Fort of Bombay is laid down and is accompanied by a scale of feet.\nThe Museum’s collection of historical maps of Mumbai illustrate the city’s evolution from a group of seven islands into a vibrant urban centre in the 19th century. Changes in geography as a result of invasions, economic booms and planning are carefully chronicled."},
    {img: bh4.src, name: "Facsimile of the map of Bombay and the district prepared for Peshwa by the Peshwa's agent in Bombay about 1770", date: "1909-12\nWatercolour & ink on paper", popupimg: popbh4.src, details: "This 18th century map was prepared for the Peshwa Madhavrao, the Maratha ruler of the Deccan and a rival of the British in erstwhile Bombay. The map is particularly interesting for its unique perspective. It was not meant to be an accurate survey of the region but rather a diagrammatic representation with symbols highlighting important information. This depiction of Mumbai (Bombay) and its harbour was probably made as part of a Maratha strategy to take control of the island."},
    {img: bh5.src, name: "Bombay View", date: "c.1860\nHandcoloured engraving", popupimg: popbh5.src, details: "This hand-coloured engraving shows the Mumbai (Bombay) harbour with tall palm trees and houses built in semi-European style with elaborately carved brackets of teak wood, painted green and red. This engraving is part of a recent acquisition of prints, lithographs, photographs, aquatints and plates dated from the 18th to early 20th centuries which enhance and compliment the Museum’s permanent display on Mumbai."},
    {img: bh6.src, name: "Weighing Cotton at Bombay for the English Market", date: "1862\nEngraving", popupimg: popbh6.src, details: "This engraving shows cotton being weighed and readied in Mumbai (Bombay) for export to England. During the years of the American Civil War (1861-65), imports of raw cotton from America into England were suspended. The English textile industry turned to western India for its cotton imports, resulting in a boom in cotton trade from Mumbai (Bombay)."},
    {img: bh7.src, name: "Street Scene of Old Bombay\nE. Hildebrandt", date: "c. mid-19th century\nLithograph print of a watercolour painting", popupimg: popbh7.src, details: "Edward Hildebrandt, 1818-1869, was a German painter of repute who travelled on a world tour from 1860-1862, which included stops in the Middle East, India, Asia and the U.S. He worked mainly in watercolours. A folio of his paintings from his world voyage was published as chromolithographs in 1864 in Berlin. The original watercolours from the voyage were exhibited in London in 1866 and at an exhibition at the Crystal Palace in 1868.\nThis painting shows an elite residential quarter of Mumbai (Bombay), as suggested by the broad street, wooden verandahs and elaborate facades of the houses."},
    {img: bh8.src, name: "Facsimile of the Island of Bombay by Captain Thomas Dickinson,", date: "816-1890 1909-12\nWatercolour & ink on paper", popupimg: popbh8.src, details: "This map titled ‘The Island of Bombay’ shows the land mass added to the islands through various reclamation projects carried out by the government between the years 1816 -1890. The survey was commenced under Capt. Thomas Dickinson, one of the East India Company’s Engineers in 1812.\nThe Museum’s collection of historical maps of Mumbai illustrate the city’s evolution from a group of seven islands into a vibrant urban centre in the 19th century. Changes in geography as a result of invasions, economic booms and planning are carefully chronicled."},
    {img: bh9.src, name: "The Town Hall, Bombay", date: "1893\nEngraving", popupimg: popbh9.src, details: "This engraving of the Town Hall building, completed in 1830, is taken from a photograph by Firth & Co., a company specialising in photographic postcards, established in Reigate, Surrey. Designed in the neo-classical style of architecture, the Town Hall was built at the heart of the Bombay Fort. It is now known as the Asiatic Society of Mumbai and houses one of the largest libraries in the country."},
    {img: bh10.src, name: "Model of a Hodi", date: "c. early 20th century\nWood, cloth and cotton thread", popupimg: popbh10.src, details: "On display at the Museum is a comprehensive collection of wooden models of native crafts used in coastal and long-distance trade from Mumbai (Bombay) in the 19th and early 20th centuries. These models were hand-crafted and donated to the Museum by the Bombay Port Trust. ‘Hodi’ is a common fishing boat, built near all coastal ports and can be pulled or sailed."},
    {img: bh11.src, name: "Flora Fountain", date: "Late 19th to early 20th century\nGlass negative", popupimg: popbh11.src, details: "This image of the Flora Fountain is part of the Museum’s collection of glass negatives. Sculpted in imported Portland stone by James Forsythe, the Flora Fountain was unveiled in 1869 and dedicated to Sir Bartle Frere, Governor of Bombay from 1862 to 1867. It was situated at the site of one of the three gateways to the erstwhile Bombay Fort. The fountain is named after Flora, the Roman goddess of Abundance, seen at the top."},
    {img: bh12.src, name: "Model of a Dredger, Kuphus", date: "Late 19th to early 20th century\nWood and metal", popupimg: popbh12.src, details: "This model of a dredger named ‘Kuphus’ was presented to the Museum by the Bombay Port Trust Authorities in 1914. Dredgers were large mechanisms used to gather sediments from sea bed which was later used for miscellaneous activities. In Mumbai (Bombay), dredgers were mainly employed for reclamation works and thus extensive stretches of land were made available for transportation, housing and businesses."},
    {img: bh13.src, name: "Kolis", date: "1909-10\nClay figurines", popupimg: popbh13.src, details: "The Kolis, a fishing community, were the original inhabitants of the seven islands of Mumbai, shown here in their traditional attire. A collection of clay models on display in the Kamalnayan Bajaj Mumbai Gallery showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. These models further illustrate art historical developments of that time and innovations in creating new art forms.\nThe Kolis continue to practice their traditional occupation and Koli villages survive along Mumbai’s coastline even today. Interestingly the name Mumbai is derived from the name of the goddess 'Mumba' worshipped by the Kolis, and 'ai' or ‘mother’ in Marathi."},
    {img: bh14.src, name: "Surati Bohras", date: "1909-10\nClay figurines", popupimg: popbh14.src, details: "These models depict a Bohra couple from Surat. The Bohras were amongst the first communities to settle in Mumbai (Bombay) after the arrival of the East India Company and played a crucial role in the development of the city as a thriving trading and industrial centre.\nA collection of clay models on display in the Kamalnayan Bajaj Mumbai Gallery showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. These models further illustrate art historical developments of that time and innovations in creating new art forms."},
    {img: bh15.src, name: "Parsis", date: "1909-10\nClay figurines", popupimg: popbh15.src, details: "These models of a Parsi gentleman and his wife depict the Zoroastrian community that migrated to India from Persia (Iran) from around 10th century to escape religious persecution. The Parsis were amongst the first communities to settle in Mumbai (Bombay) after the arrival of the East India Company and played a crucial role in the development of the city as a thriving trading and industrial centre.\nA collection of clay models on display in the Kamalnayan Bajaj Mumbai Gallery showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. These models further illustrate art historical developments of that time and innovations in creating new art forms."},
    {img: bh16.src, name: "Baghdadi Jews", date: "1909-10\nClay figurines", popupimg: popbh16.src, details: "This model is of a Baghdadi Jew and his wife.The Baghdadi Jews were among the foreign communities that migrated to Mumbai (Bombay) during the 18th and 19th centuries. Many of these Jewish families resided in Byculla, where the Museum is located. The models are shown dressed in traditional Jewish clothes and headwear. Jews were also known as ‘Yahudis’ in India.\nA collection of clay models on display in the Kamalnayan Bajaj Mumbai Gallery showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. These models further illustrate art historical developments of that time and innovations in creating new art forms."},
    {img: bh17.src, name: "Dhobis", date: "1909-10\nClay figurines", popupimg: popbh17.src, details: "These models depict a washer man or Dhobi and his wife, shown with bundles of clothes tied to their backs. Dhobis remain a common sight in the city even today.\nA collection of clay models on display in the Kamalnayan Bajaj Mumbai Gallery showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. These models further illustrate art historical developments of that time and innovations in creating new art forms."},
    {img: bh18.src, name: "People of Mumbai", date: "1930\nPlaster of paris and clay figurines", popupimg: popbh18.src, details: "Pride of place has been given to the people of the city in the Kamalnayan Bajaj Mumbai Gallery. The Headwear case depicts the distinct styles of traditional headgear worn by the various communities in Mumbai, showcasing the city’s diversity and cosmopolitanism.\nThe establishment of East India Company’s headquarters in Mumbai (Bombay) provided the catalyst for migration to the region from 16th century onwards. The East India Company invited communities from within India and outside to settle in Mumbai (Bombay) and help develop trade and business. They were offered economic opportunity and social and religious freedoms as a result of which many communities migrated to the city and contributed to its development in their unique ways."},
    {img: bh19.src, name: "Model of Worli area after development", date: "early 20th century\nRelief Map", popupimg: popbh19.src, details: "A relief map of Worli estates after development shows the topography of the Worli area after the establishment of the mills. Clearly visible are the mills and residential quarters of the workers. The dense residential buildings reflect the influx of migrants who came to Mumbai to work in the mills of Mumbai (Bombay).\nThe Museum’s collection of historical maps of Mumbai illustrate the city’s evolution from a group of seven islands into a vibrant urban centre in the 19th century. Changes in geography as a result of invasions, economic booms and planning are carefully chronicled."},
    {img: bh20.src, name: "Bellasis Road Chawls", date: "early 20th century\nDiorama", popupimg: popbh20.src, details: "This diorama of Bellasis Road Chawls, located in Mumbai Central, was loaned by the Estate Agent and Land Manager of Bombay Municipal Corporation to the Museum in 1954.\nThe development of the cotton and textile mill industry in Mumbai (Bombay) encouraged large-scale migration to the city. There was a need to create affordable housing for all the workers and different areas in the city were earmarked for developing residential areas. Small apartments known as ‘chawls’ with common facilities and shared verandahs were constructed for housing immigrants."},
]