import emp1 from "@/public/collection/early-modern/1.jpg"
import emp2 from "@/public/collection/early-modern/2.jpg"
import emp3 from "@/public/collection/early-modern/3.jpg"
import emp4 from "@/public/collection/early-modern/4.jpg"
import emp5 from "@/public/collection/early-modern/5.jpg"
import emp6 from "@/public/collection/early-modern/6.jpg"
import emp7 from "@/public/collection/early-modern/7.jpg"
import emp8 from "@/public/collection/early-modern/8.jpg"
import emp9 from "@/public/collection/early-modern/9.jpg"
import emp10 from "@/public/collection/early-modern/10.jpg"
import emp11 from "@/public/collection/early-modern/11.jpg"
import emp12 from "@/public/collection/early-modern/12.jpg"
import emp13 from "@/public/collection/early-modern/13.jpg"
import emp14 from "@/public/collection/early-modern/14.jpg"
import emp15 from "@/public/collection/early-modern/15.jpg"
import emp16 from "@/public/collection/early-modern/16.jpg"
import emp17 from "@/public/collection/early-modern/17.jpg"
import emp18 from "@/public/collection/early-modern/18.jpg"
import emp19 from "@/public/collection/early-modern/19.jpg"
import emp20 from "@/public/collection/early-modern/20.jpg"
import emp21 from "@/public/collection/early-modern/21.jpg"
import emp22 from "@/public/collection/early-modern/22.jpg"
import emp23 from "@/public/collection/early-modern/23.jpg"
import emp24 from "@/public/collection/early-modern/24.jpg"

import popemp1 from "@/public/collection/early-modern/popups/pop53.jpg"
import popemp2 from "@/public/collection/early-modern/popups/pop54.jpg"
import popemp3 from "@/public/collection/early-modern/popups/pop55.jpg"
import popemp4 from "@/public/collection/early-modern/popups/pop56.jpg"
import popemp5 from "@/public/collection/early-modern/popups/pop57.jpg"
import popemp6 from "@/public/collection/early-modern/popups/pop58.jpg"
import popemp7 from "@/public/collection/early-modern/popups/pop60.jpg"
import popemp8 from "@/public/collection/early-modern/popups/pop61.jpg"
import popemp9 from "@/public/collection/early-modern/popups/pop62.jpg"
import popemp10 from "@/public/collection/early-modern/popups/pop63.jpg"
import popemp11 from "@/public/collection/early-modern/popups/pop64.jpg"
import popemp12 from "@/public/collection/early-modern/popups/pop65.jpg"
import popemp13 from "@/public/collection/early-modern/popups/pop66.jpg"
import popemp14 from "@/public/collection/early-modern/popups/pop67.jpg"
import popemp15 from "@/public/collection/early-modern/popups/pop68.jpg"
import popemp16 from "@/public/collection/early-modern/popups/pop77.jpg"
import popemp17 from "@/public/collection/early-modern/popups/pop69.jpg"
import popemp18 from "@/public/collection/early-modern/popups/pop70.jpg"
import popemp19 from "@/public/collection/early-modern/popups/pop71.jpg"
import popemp20 from "@/public/collection/early-modern/popups/pop72.jpg"
import popemp21 from "@/public/collection/early-modern/popups/pop73.jpg"
import popemp22 from "@/public/collection/early-modern/popups/pop74.jpg"
import popemp23 from "@/public/collection/early-modern/popups/pop75.jpg"
import popemp24 from "@/public/collection/early-modern/popups/pop76.jpg"

export const earlyModern = [
    {img: emp1.src, name: "Bombay School Pottery", date: "Late 19th to early 20th century\nCeramic", popupimg: popemp1.src, details:"Among the earliest experiments carried out at the Bombay School of Art or the Sir J.J. School of Art, Mumbai were the successful efforts to improve the production of different types of pottery. The workshops experimented with new types of clays, glazes, forms and designs. The floral patterns and colours observed on this glazed vase seem to be inspired by Art Noveau designs. The form of this pot is similar to classical Greek and Roman pottery as the School was experimenting with new techniques and forms. This pottery was much admired and popular at international exhibitions." },
    {img: emp2.src, name: "Courtscene (detail) Rao Bahadur M.V. Dhurandhar", date: "Early 20th century\nWatercolour on paper", popupimg: popemp2.src, details: "Renowned artist Mahadev Vishwanath Dhurandhar studied at the Sir J. J. School of Art between 1890 and 1895. He was also the first Indian director (1919-1935) of the School of Art. Particularly skilled with watercolours, Dhurandhar became an illustrator and portraitist of great repute. He depicted his subjects with authenticity and sympathy, creating a unique visual record of contemporary Mumbai (Bombay) that has not been matched in any other city in India\nThis painting acquired by the Museum in 1928 depicts a court scene in the theatrical tradition of western history painting."},
    {img: emp3.src, name: "Street Scene, Bombay, Baburao Sadwelkar", date: "Early 20th century\nWatercolour on paper", popupimg: popemp3.src, details: "Baburao Sadwelkar (1928 - 2000) studied at the Sir J. J. School of Art where he became deeply influenced by prominent European impressionist artists. This influence is visible in his works, which mostly consist of portraits and landscapes. This painting of a street scene depicts the Crawford Market area, the biggest market place in Mumbai."},
    {img: emp4.src, name: "Bombay School Pottery", date: "Late 19th to early 20th century\nCeramic", popupimg: popemp4.src, details: "Among the earliest experiments carried out at the Sir J.J. School of Art were the successful efforts to improve the production of different types of pottery. Experiments with pottery at the George C. Clark workshop at the Sir J.J School of Art produced a range of colours and forms that were very popular in Europe and India. The most popular tints used in the Bombay School Pottery were white, blue or turquoise, dark blue, dark green, gold, and flesh. This flower vase with a narrow neck and saffron coloured glaze is one such example of pottery produced by the students at the J.J. School of Art. This kind of pottery was very popular in the Western market and at the international exhibitions."},
    {img: emp5.src, name: "Bombay School Pottery", date: "Late 19th to early 20th century\nCeramic", popupimg: popemp5.src, details: "The glazed ceramic ware known as Bombay School Pottery was made in an experimental kiln set up by Mr. Terry, the superintendent of the Sir. J.J School of Art. Mr. Terry introduced a new range of shapes and experimented with clay from different regions to make durable pottery. This vase demonstrates a blend of western form and design inspired by a traditional Indian motif, the peacock feather. This pottery was much admired and popular at international exhibitions."},
    {img: emp6.src, name: "Carpet, Bombay School of Art", date: "Late 19th to Early 20th century", popupimg: popemp6.src, details: "This floral patterned carpet was acquired by the Museum in 1906 as part of a set of five carpets. It was manufactured in the Reay Art Workshop at the Sir J. J School of Art (formerly known as the Bombay School of Art). The Reay Art workshop was set up in 1890 to promote regional crafts like wood carving, pottery, silver and copper work and carpet weaving. Some of the specimens from this set were loaned to the Principal of the School of Art to exhibit in the Bombay Section of the Allahabad Exhibition between the years 1910-11."},
    {img: emp7.src, name: "Dilruba", date: "c. 1925\nWood, ivory and metal", popupimg: popemp7.src, details: "The word 'dilruba' has its origin in the Persian language and may be defined as 'the one who steals your heart'. It is a stringed instrument played with a bow and constructed of wood and animal skin. This musical instrument was acquired by the Museum in 1925."},
    {img: emp8.src, name: "Maratha Lady\nRao Bahadur M.V. Dhurandhar,", date: "1916\nWatercolour on paper", popupimg: popemp8.src, details: "Renowned artist Mahadev Vishwanath Dhurandhar studied at the Sir J. J. School of Art between 1890 and 1895. He was also the first Indian director (1919-1935) of the School of Art. Particularly skilled with watercolours, Dhurandhar became an illustrator and portraitist of great repute. He depicted his subjects with authenticity and sympathy, creating a unique visual record of contemporary Mumbai (Bombay) that has not been matched in any other city in India\nThis painting, acquired by the Museum in 1916, depicts a lady from the Maratha community in traditional attire."},
    {img: emp9.src, name: "CL Burns, curator\nVictoria & Albert Museum, Bombay", date: "1903-18\nPrint from glass negative", popupimg: popemp9.src, details: "This photograph from the Museum’s collection of glass negatives shows Mr. Cecil L. Burns, an ex-curator of the Dr. Bhau Daji Lad Museum (formerly the Victoria & Albert Museum) seated in the centre with his staff. Mr. Burns also held the position of Dean of the School of Art. On assuming charge of the Victoria and Albert Museum in 1903, he created a collection of maps, plans, prints and photographs illustrating the history of the city of Mumbai (Bombay)."},
    {img: emp10.src, name: "Portrait of Jamsetjee\nJeejeebhoy", date: "", popupimg: popemp10.src, details: "Sir Jamshetjee Jeejeebhoy (1783-1859) was a notable businessman, philanthropist and one of the most prominent citizens of Mumbai. His philanthropy extended towards setting up hospitals, schools, charities and public buildings. The Sir Jamshetjee Jeejeebhoy School of Art, formerly known as the Bombay School of Art, was set up due to his support. He also donated generously towards the establishment of the Dr. Bhau Daji Lad Museum, then the Victoria & Albert Museum, Bombay\nThis photograph of Jeejeebhoy from the Museum’s collection is an example of early portrait photography, which mimics elements of chiaroscuro, single-point perspective or having the sitter facing the painter or photographer at eye level."},
    {img: emp11.src, name: "Prabhu Lady\nRao Bahadur M.V. Dhurandhar", date: "1916\nWatercolour on paper", popupimg: popemp11.src, details: "Renowned artist Mahadev Vishwanath Dhurandhar studied at the Sir J. J. School of Art between 1890 and 1895. He was also the first Indian director (1919-1935) of the School of Art. Particularly skilled with watercolours, Dhurandhar became an illustrator and portraitist of great repute. He depicted his subjects with authenticity and sympathy, creating a unique visual record of contemporary Mumbai (Bombay) that has not been matched in any other city in India\nThis painting depicts a lady from the Prabhu community in Mumbai dressed in traditional attire."},
    {img: emp12.src, name: "Seascapes of Bombay seashore\nP.A. Dhond", date: "20th century\nWatercolour on paper", popupimg: popemp12.src, details: "Prominent amongst the Museum's collection of late 19th- early 20th century paintings executed by artists of the Sir J. J. School of Art are the watercolours of P. A. Dhond (1908 - 2001). Inspired by the land and sea-scapes of coastal Maharashtra, where he was raised, Dhond's watercolours would become the artist's most celebrated works."},
    {img: emp13.src, name: "Street Scene, Bombay\nBaburao Sadwelkar", date: "Early 20th century\nWatercolour on paper", popupimg: popemp13.src, details: "Baburao Sadwelkar (1928 - 2000) studied at the Sir J. J. School of Art. At the School of Art, he became deeply influenced by prominent European impressionist artists. This influence is visible in his works, which mostly consist of portraits and landscapes. This painting of a street scene depicts the Crawford Market area, the biggest market place in Mumbai."},
    {img: emp14.src, name: "V.T. Station in Monsoon\nP.A. Dhond", date: "1958\nWatercolour on paper", popupimg: popemp14.src, details: "Prominent amongst the Museum's collection of late 19th- early 20th century paintings executed by artists of the Sir J. J. School of Art are the watercolours of P. A. Dhond (1908 - 2001). Inspired by the land and sea-scapes of coastal Maharashtra, where he was raised, Dhond's watercolours would become the artist's most celebrated works."},
    {img: emp15.src, name: "Village Technical School", date: "1957\nDiorama with clay models", popupimg: popemp15.src, details: "Technical Schools were established in the Presidency towns of Bombay, Calcutta and Madras as well as at other important places such as Jaipur and Lucknow to improve public standards for good design. In the early days, these schools taught everything from dance and music to carpentry and pottery, as well as other 'technical' skills such as drawing and painting\nThis diorama from the mid-20th century depicts a technical school. It shows a school building with classrooms, a Museum Room, a Tool-House and Workshop. Students are portrayed learning weaving, carpentry, rope making, cultivation, ornamental gardening, music, dance and various crafts."},
    {img: emp16.src, name: "Occupations", date: "Late 19th to early 20th century\nClay models", popupimg: popemp16.src, details: "The Museum’s collection of clay models and dioramas document people, lifestyles and culture in Mumbai from the late 19th to the early 20th century. These models made at the Museum in early 1900’s represent different occupations of that period. They also provide the visitors with an insight into the economics of the city of Mumbai. Many of these occupations are still practiced in the city, as well as the country, even today."},
    {img: emp17.src, name: "Cobbler Patna", date: "Late 19th to early 20th century\nMica painting", popupimg: popemp17.src, details: "The Museum’s collection of mica paintings represent aspects of traditional Indian lifestyle and people engaged in various occupations, such as the cobbler depicted here. Mica sheets have a smooth, polished and reflective surface. These paintings from the Patna School are executed on mica sheets the size of a postcard, using paint, which was mixed with a binding material, and applied by a thin brush. Mica paintings were popular among the European visitors to India, who purchased them as souvenirs."},
    {img: emp18.src, name: "Diwan-i-Khas, Delhi Fort", date: "Early 20th century\nPainting on Ivory", popupimg: popemp18.src, details: "This ivory painting of the Diwan-i-Khas at the Delhi Fort was made by an artist named U.H. Sharif Husein Khan. It was acquired by the Museum in 1929. Diwan-i-khas was the hall of private audiences where Mughal emperors met with courtiers and state guests.\nMiniature paintings on ivory were a popular art form in the Indian subcontinent. Thin translucent sheets of ivory were roughened and de-greased to make the surface retain paint. They were then bleached in the sun to make them whiter and the colours were made stickier by adding a binding material. George Birdwood, one of the Museum’s earliest curators, notes that painting on ivory was coveted by both the Indian and European elites."},
    {img: emp19.src, name: "Hindoo Natch Girls, Coleman", date: "F. - 1899\nColoured Print", popupimg: popemp19.src, details: "This print titled Hindoo Natch Girls was first published in the F. M Coleman edited publication, ‘Typical Pictures of Indian Natives’, in 1897. This book consists of a collection of hand-coloured photographs depicting costumes worn by Indians of various castes and occupations. Such picture portraits initiated a genre of popular imagery which was reproduced on postcards and purchased by Europeans during their travels in India.\nThis hand coloured photograph depicts Hindoo nautch girls or dancing girls. Nautches or public dance performances were arranged by the elite classes of the society on special occasions and many distinguished Company officers were invited to such performances."},
    {img: emp20.src, name: "Indian Aborigines (Natives), Giulio Ferrario", date: "1823-1830\nColoured aquatint", popupimg: popemp20.src, details: "This coloured aquatint depicting different people is by Giulio Ferrario, an artist, publisher and printer from Milan, Italy. His monumental work ‘Il costume antico e moderno…’ contained over 1,600 hand coloured aquatints and engravings depicting people of various regions and countries dressed in traditional attire."},
    {img: emp21.src, name: "Jodhabai", date: "Early 20th century\nPainting on ivory", popupimg: popemp21.src, details: "Miniature paintings on ivory were a popular art form in the Indian subcontinent. Thin translucent sheets of ivory were roughened and de-greased to make the surface retain paint. They were then bleached in the sun to make them whiter and the colours were made stickier by adding a binding material. By the end of the 18th century, miniature portraits on ivory demonstrated European influence on form and composition, such as this exquisite example of the Empress Jodhabai, queen of the Mughal ruler Akbar, from the Rajput School. George Birdwood, one of the Museum’s earliest curators, notes that painting on ivory was coveted by both the Indian and European elites."},
    {img: emp22.src, name: "Saumpareeah or Snake Catcher, Doyley", date: "C. - 1813\nHandcoloured Aquatint", popupimg: popemp22.src, details: "This aquatint titled Saumpareeah or Snake Catcher by Sir Charles Doyley was published in a book consisting of twenty aquatints in 1813, titled ‘The European in India’. The purpose of the book was to introduce the reader to the lifestyle of a Company servant with a language that was instructive as well as amusing. This drawing reflects the popular imagery of India and gives the reader an insight into the life of a Company officer in pre-imperial India. This image shows a snake catcher or a ‘Saumpareeah’ who is playing an instrument and exhibiting snakes before the Europeans."},
    {img: emp23.src, name: "Thug, People of Mumbai", date: "Late 19th to early 20th century\nClay model", popupimg: popemp23.src, details: "The Museum’s collection of clay models and dioramas document people, lifestyles and culture in Mumbai from the late 19th to the early 20th century. This model of a thug is depicted with a large moustache and has a fearsome appearance. The controversial term 'thug' was coined during the colonial period and used by the British Government in India. . Thugs were said to be the followers of Hindu Goddess Kali and were known during the colonial era for their organized conspiracy of robbery and murder. Imprisoned thugs were often taught handicraft skills such as making carpets."},
    {img: emp24.src, name: "Village Life (detail)", date: "Early 20th century\nDiorama with clay models", popupimg: popemp24.src, details: "The models and dioramas, crafted to document the lifestyle and culture of Mumbai in the 19th and 20th centuries further illustrate contemporary art historical developments and innovations in creating new art forms. This diorama created in 1935-36 showcasing a rural Indian village depicts the existing conditions and the 'ideal' for village life and agriculture in India, as imagined and planned by the British in the late 19th century. Given the lack of film and video at the time, museums were an important medium through which to reach the public. Similar dioramas were showcased in various international exhibitions."},
]