import mc1 from "@/public/collection/modern-contemporary/1.jpg"
import mc2 from "@/public/collection/modern-contemporary/2.jpg"
import mc3 from "@/public/collection/modern-contemporary/3.jpg"
import mc4 from "@/public/collection/modern-contemporary/4.jpg"
import mc5 from "@/public/collection/modern-contemporary/5.jpg"
import mc6 from "@/public/collection/modern-contemporary/6.jpg"
import mc7 from "@/public/collection/modern-contemporary/7.jpg"
import mc8 from "@/public/collection/modern-contemporary/8.jpg"
import mc9 from "@/public/collection/modern-contemporary/9.jpg"
import mc10 from "@/public/collection/modern-contemporary/10.jpg"
import mc11 from "@/public/collection/modern-contemporary/11.jpg"
import mc12 from "@/public/collection/modern-contemporary/12.jpg"

import popmc1 from "@/public/collection/modern-contemporary/popups/pop26.jpg"
import popmc2 from "@/public/collection/modern-contemporary/popups/pop27.jpg"
import popmc3 from "@/public/collection/modern-contemporary/popups/pop28.jpg"
import popmc4 from "@/public/collection/modern-contemporary/popups/pop30.jpg"
import popmc5 from "@/public/collection/modern-contemporary/popups/pop25.jpg"
import popmc6 from "@/public/collection/modern-contemporary/popups/pop29.jpg"
import popmc7 from "@/public/collection/modern-contemporary/popups/pop24.jpg"
import popmc8 from "@/public/collection/modern-contemporary/popups/pop31.jpg"
import popmc9 from "@/public/collection/modern-contemporary/popups/pop32.jpg"
import popmc10 from "@/public/collection/modern-contemporary/popups/pop21.jpg"
import popmc11 from "@/public/collection/modern-contemporary/popups/pop22.jpg"
import popmc12 from "@/public/collection/modern-contemporary/popups/pop23.jpg"

export const modernContemporary = [
    {img: mc1.src, name: "Listening to the Shades\nNalini Malani", date: "2014\nFacsimile printed reverse paintings", popupimg: popmc1.src, details:"Listening to the Shades is an artist’s book by Nalini Malani and Robert Storr, inspired by the writing of Christa Wolf on the ancient Greek myth of Cassandra. The forty-two facsimile printed reverse paintings, tells the story of Cassandra’s insights being ignored and considered heretical. In the contemporary context, she symbolizes the unfinished business of the women’s revolution - a woman’s thoughts and premonitions are not understood and recognized. Malani's breathtaking rendering of this classic narrative has deep resonance with the many challenges that women still face in every culture. Artist Nalini Malani donated a copy of the 42 facsimile prints, Listening to the Shades, to the Museum in February 2014." },
    {img: mc2.src, name: "Listening to the Shades\nNalini Malani", date: "2014\nFacsimile printed reverse paintings", popupimg: popmc2.src, details: "Listening to the Shades is an artist’s book by Nalini Malani and Robert Storr, inspired by the writing of Christa Wolf on the ancient Greek myth of Cassandra. The forty-two facsimile printed reverse paintings, tells the story of Cassandra’s insights being ignored and considered heretical. In the contemporary context, she symbolizes the unfinished business of the women’s revolution - a woman’s thoughts and premonitions are not understood and recognized. Malani's breathtaking rendering of this classic narrative has deep resonance with the many challenges that women still face in every culture. Artist Nalini Malani donated a copy of the 42 facsimile prints, Listening to the Shades, to the Museum in February 2014."},
    {img: mc3.src, name: "Listening to the Shades\nNalini Malani", date: "2014\nFacsimile printed reverse paintings", popupimg: popmc3.src, details: "Listening to the Shades is an artist’s book by Nalini Malani and Robert Storr, inspired by the writing of Christa Wolf on the ancient Greek myth of Cassandra. The forty-two facsimile printed reverse paintings, tells the story of Cassandra’s insights being ignored and considered heretical. In the contemporary context, she symbolizes the unfinished business of the women’s revolution - a woman’s thoughts and premonitions are not understood and recognized. Malani's breathtaking rendering of this classic narrative has deep resonance with the many challenges that women still face in every culture. Artist Nalini Malani donated a copy of the 42 facsimile prints, Listening to the Shades, to the Museum in February 2014."},
    {img: mc4.src, name: "POI/Bharat ke Log\nArchana Hande", date: "2014\nVideo, sound, clay\nplaster models, mosquito net", popupimg: popmc4.src, details: "POI/Bharat ke Log by artist Archana Hande is a multi-media installation that consists of a printed mosquito net measuring 12ft in height, 2 videos of 45 minutes and 5 minutes each and 1 audio file. Hande uses the idea of a mosquito net – a British import now used ubiquitously in India – as the protective layer which encloses the ephemeral images of the hundreds of types of people which she has sourced both from the Museum’s collection as well as her own. Hande creates a topography of images both contemporary and historic that emerge like ghosts and disappear in a shroud that is actually a mosquito net, ephemera from the past seeking to inhabit a tangible form in the here and now. Using video, assemblage, popular imagery and sounds to create an immersive experience the artist asks the viewer to reflect on who we are and how we have come to see ourselves.\nPOI/Bharat ke Log by Archana Hande was commissioned for the Museum in 2014 and opened to the public in October 2014."},
    {img: mc5.src, name: "POI/Bharat ke Log\nArchana Hande", date: "2014\nVideo, sound, clay\nplaster models, mosquito net", popupimg: popmc5.src, details: "POI/Bharat ke Log by artist Archana Hande is a multi-media installation that consists of a printed mosquito net measuring 12ft in height, 2 videos of 45 minutes and 5 minutes each and 1 audio file. Hande uses the idea of a mosquito net – a British import now used ubiquitously in India – as the protective layer which encloses the ephemeral images of the hundreds of types of people which she has sourced both from the Museum’s collection as well as her own. Hande creates a topography of images both contemporary and historic that emerge like ghosts and disappear in a shroud that is actually a mosquito net, ephemera from the past seeking to inhabit a tangible form in the here and now. Using video, assemblage, popular imagery and sounds to create an immersive experience the artist asks the viewer to reflect on who we are and how we have come to see ourselves.\nPOI/Bharat ke Log by Archana Hande was commissioned for the Museum in 2014 and opened to the public in October 2014."},
    {img: mc6.src, name: "POI/Bharat ke Log\nArchana Hande", date: "2014\nVideo, sound, clay\nplaster models, mosquito net", popupimg: popmc6.src, details: "POI/Bharat ke Log by artist Archana Hande is a multi-media installation that consists of a printed mosquito net measuring 12ft in height, 2 videos of 45 minutes and 5 minutes each and 1 audio file. Hande uses the idea of a mosquito net – a British import now used ubiquitously in India – as the protective layer which encloses the ephemeral images of the hundreds of types of people which she has sourced both from the Museum’s collection as well as her own. Hande creates a topography of images both contemporary and historic that emerge like ghosts and disappear in a shroud that is actually a mosquito net, ephemera from the past seeking to inhabit a tangible form in the here and now. Using video, assemblage, popular imagery and sounds to create an immersive experience the artist asks the viewer to reflect on who we are and how we have come to see ourselves.\nPOI/Bharat ke Log by Archana Hande was commissioned for the Museum in 2014 and opened to the public in October 2014."},
    {img: mc7.src, name: "Untitled (Cobweb/Crossings)\nReena Kallat", date: "2013\nPainted sculptural installation in FRP and metal", popupimg: popmc7.src, details: "Reena Kallat’s Untitled (Cobweb/Crossings) is an over-sized web formed with hundreds of rubber-stamps, each one bearing the colonial name of the city street that, in present day Mumbai, has been replaced by an indigenous name. By recovering the memory of one aspect of the process of decolonization - the renaming of anglicised British street names with Indian or regional ones - it forms a palimpest on to which generations re-inscribe stories. The work is comprised of resin rubber stamps, steel rope, steel hooks and measured approximately 45 ft. in height and 60 ft. in width.\nUntitled (Cobweb/Crossings) was part of the collaborative project ZegnaArt Public/India, between the Ermenogildo Zegna Group and the Dr. Bhau Daji Lad Museum, the installation  was commissioned for the Museum and unveiled to the public in March 2013."},
    {img: mc8.src, name: "Untitled (Cobweb/Crossings)\nReena Kallat,", date: "2013\nPainted sculptural installation in FRP and metal", popupimg: popmc8.src, details: "Reena Kallat’s Untitled (Cobweb/Crossings) is an over-sized web formed with hundreds of rubber-stamps, each one bearing the colonial name of the city street that, in present day Mumbai, has been replaced by an indigenous name. By recovering the memory of one aspect of the process of decolonization - the renaming of anglicised British street names with Indian or regional ones - it forms a palimpest on to which generations re-inscribe stories. The work is comprised of resin rubber stamps, steel rope, steel hooks and measured approximately 45 ft. in height and 60 ft. in width.\nUntitled (Cobweb/Crossings) was part of the collaborative project ZegnaArt Public/India, between the Ermenogildo Zegna Group and the Dr. Bhau Daji Lad Museum, the installation  was commissioned for the Museum and unveiled to the public in March 2013."},
    {img: mc9.src, name: "Untitled (Cobweb/Crossings)\nReena Kallat", date: "2013\nPainted sculptural installation in FRP and metal", popupimg: popmc9.src, details: "Reena Kallat’s Untitled (Cobweb/Crossings) is an over-sized web formed with hundreds of rubber-stamps, each one bearing the colonial name of the city street that, in present day Mumbai, has been replaced by an indigenous name. By recovering the memory of one aspect of the process of decolonization - the renaming of anglicised British street names with Indian or regional ones - it forms a palimpest on to which generations re-inscribe stories. The work is comprised of resin rubber stamps, steel rope, steel hooks and measured approximately 45 ft. in height and 60 ft. in width.\nUntitled (Cobweb/Crossings) was part of the collaborative project ZegnaArt Public/India, between the Ermenogildo Zegna Group and the Dr. Bhau Daji Lad Museum, the installation  was commissioned for the Museum and unveiled to the public in March 2013."},
    {img: mc10.src, name: "Untitled, Anonymous", date: "Gouache on card", popupimg: popmc10.src, details: "This painting which depicts cowherds and their cattle in a rural setting, was acquired by the Museum in 2012. It was part of a larger cache of 43 exquisite small-format gouache works, by those associated with the Sir. J.J. School in the early 20th century. These works offer valuable insights into the School’s formative period as well as the beginnings of Indian modernism. They also complement the Museum’s permanent collection of decorative objects and paintings made by students of the Sir. J.J. School of Art. These works are illustrative of the revivalist ‘Indian Renaissance’ art movement of the time, which drew inspiration from classical Indian art practices, specifically, in this case, the earlier tradition of Rajput painting."},
    {img: mc11.src, name: "Untitled, Cecil Burns", date: "1918\nWatercolour on paper", popupimg: popmc11.src, details: "Cecil L. Burns, was the Dean of the Sir. J.J. School of Art, as well as one of the early curators of the Museum. This work, acquired in 2012, depicts a lily pond and shows his skill in rendering water colours rather skilfully. It could have perhaps been intended as a demonstration for his students. It was part of a larger cache of 43 exquisite small-format gouache works, by those associated with the Sir. J.J. School in the early 20th century. These works offer valuable insights into the School’s formative period as well as the beginnings of Indian modernism."},
    {img: mc12.src, name: "Untitled, Subhadra Anandkar", date: "1950\nGouache on card", popupimg: popmc12.src, details: "In prominence in this post-Independence painting is the popular Indian ritual of a baby’s bath ritual, featuring in the foreground the maalish or massage with oil. The two women in front appear to be the protagonists with a baby between them: one oiling his hair, the other massaging his body. This commonplace scene seems to take place in a rural courtyard, with other women going about their chores or catching up on news. The foliage is stylised, along with the drapes of the womens’ nine yard sarees, the latter so characteristic of rural living. It was part of a larger cache of 43 exquisite small-format gouache works, by those associated with the J.J. School in the early 20th century. These works offer valuable insights into the School’s formative period as well as the beginnings of Indian modernism."},
]