import trade1 from "@/public/collection/trade-cultural/trade-01.jpg"
import trade2 from "@/public/collection/trade-cultural/trade-02.jpg"
import trade3 from "@/public/collection/trade-cultural/trade-03.jpg"
import trade4 from "@/public/collection/trade-cultural/trade-04.jpg"
import trade5 from "@/public/collection/trade-cultural/trade-05.jpg"
import trade6 from "@/public/collection/trade-cultural/trade-06.jpg"
import trade7 from "@/public/collection/trade-cultural/trade-07.jpg"
import trade8 from "@/public/collection/trade-cultural/trade-08.jpg"
import trade9 from "@/public/collection/trade-cultural/trade-09.jpg"
import trade10 from "@/public/collection/trade-cultural/trade-10.jpg"
import trade11 from "@/public/collection/trade-cultural/trade-11.jpg"
import trade12 from "@/public/collection/trade-cultural/trade-12.jpg"
import trade13 from "@/public/collection/trade-cultural/trade-13.jpg"
import trade14 from "@/public/collection/trade-cultural/trade-14.jpg"
import trade15 from "@/public/collection/trade-cultural/trade-15.jpg"
import trade16 from "@/public/collection/trade-cultural/trade-16.jpg"
import trade17 from "@/public/collection/trade-cultural/trade-17.jpg"
import trade18 from "@/public/collection/trade-cultural/trade-18.jpg"
import trade19 from "@/public/collection/trade-cultural/trade-19.jpg"
import trade20 from "@/public/collection/trade-cultural/trade-20.jpg"

import poptrade1 from "@/public/collection/trade-cultural/popups/pop33.jpg"
import poptrade2 from "@/public/collection/trade-cultural/popups/pop34.jpg"
import poptrade3 from "@/public/collection/trade-cultural/popups/pop35.jpg"
import poptrade4 from "@/public/collection/trade-cultural/popups/pop36.jpg"
import poptrade5 from "@/public/collection/trade-cultural/popups/pop37.jpg"
import poptrade6 from "@/public/collection/trade-cultural/popups/pop38.jpg"
import poptrade7 from "@/public/collection/trade-cultural/popups/pop39.jpg"
import poptrade8 from "@/public/collection/trade-cultural/popups/pop40.jpg"
import poptrade9 from "@/public/collection/trade-cultural/popups/pop41.jpg"
import poptrade10 from "@/public/collection/trade-cultural/popups/pop42.jpg"
import poptrade11 from "@/public/collection/trade-cultural/popups/pop43.jpg"
import poptrade12 from "@/public/collection/trade-cultural/popups/pop44.jpg"
import poptrade13 from "@/public/collection/trade-cultural/popups/pop45.jpg"
import poptrade14 from "@/public/collection/trade-cultural/popups/pop46.jpg"
import poptrade15 from "@/public/collection/trade-cultural/popups/pop47.jpg"
import poptrade16 from "@/public/collection/trade-cultural/popups/pop48.jpg"
import poptrade17 from "@/public/collection/trade-cultural/popups/pop49.jpg"
import poptrade18 from "@/public/collection/trade-cultural/popups/pop50.jpg"
import poptrade19 from "@/public/collection/trade-cultural/popups/pop51.jpg"
import poptrade20 from "@/public/collection/trade-cultural/popups/pop52.jpg"

export const tradeCulturalExchange = [
    {img: trade1.src, name: "Ardhanareshwar, South India", date: "Late 19th to early 20th century\nBronze", popupimg: poptrade1.src, details:"The androgynous form of Ardhanareshwar is symbolic of the unity of male and female powers in God. This idol, cast in bronze, depicts the skill of Indian sculptors. Bronze is an alloy of copper, tin and zinc and is preferred by sculptors as it is durable." },
    {img: trade2.src, name: "Bowl", date: "Late 19th to early 20th century\nPapier-mache", popupimg: poptrade2.src, details: "Decorated in a Chinar leaf pattern with foliage and birds in gold on a deep red background, this bowl is one of the highlights of the Museum’s exquisite papier-mache collection from Kashmir.\nPapier-mache is the technique of creating objects using paper pieces or paper pulp moulded in the desired shape and bound with an adhesive. This delicate decorative art was introduced to Kashmir from Samarkhand in Central Asia, in the 15th century A.D. In Kashmir style of papier-mache, the paper is never completely beaten into pulp; it is softened with water and then pasted in a mould layer by layer to achieve the desired thickness."},
    {img: trade3.src, name: "Dattatreya, Mumbai", date: "Late 19th to early 20th century\nBrass", popupimg: poptrade3.src, details: "Dattatreya, a Hindu deity, is an aspect of the Trimurti, the Divine Trinity of Brahma, Vishnu and Shiva. This Dattatreya idol illustrates the naturalistic form which developed in response to European influence on Indian art. It can be distinguished from other paramparik, or traditional, idols in the Museum's collection that conform to traditional iconographic conventions."},
    {img: trade4.src, name: "Dish, Agra", date: "Late 19th to early 20th century\nSoapstone", popupimg: poptrade4.src, details: "The intricate carving on this plate from Agra, blends Islamic geometric design with European foliage patterns.\nSoapstone, a type of metamorphic rock, is known for its extreme softness and permits delicate treatment in design and workmanship. Agra is the principal centre for this art form in India, where the stone carvers also specialise in the inlaid marble work for which the city is better known."},
    {img: trade5.src, name: "Dragon Lampstand, Nepal", date: "Brass", popupimg: poptrade5.src, details: "This lampstand is an example of the decorative articles that were exported to Europe through the Asian subcontinent as land and sea trade expanded in the late 19th century. This dragon from Nepal has wings, an expressive ferocious face, a highly decorated tail and a candle stand, which it holds on its right foreleg."},
    {img: trade6.src, name: "Tushta, Bidar", date: "Late 19th - early 20th century\nSilver inlay on zinc alloy", popupimg: poptrade6.src, details: "The art of silver inlay on zinc alloy flourished in Bidar, Deccan, under the Bahamani kingdom. Influenced by Persian and Arabic damascene techniques and designs, Bidriware was a status symbol in Indian society and tushtas were used by the nobility. This Tushta or a washbasin, adorned with the poppy flower motif, has a perforated lid. It is part of the Bidricollection that was acquired from the famous art collector Purshottam Mavji in1940."},
    {img: trade7.src, name: "Fruit Container", date: "Late 19th to early 20th century\nSilver", popupimg: poptrade7.src, details: "Decorative objects made of silver were in high demand in the European market. Different provinces in India produced silver objects, each with their own distinct styles. The silver fruit bowl from Chennai (Madras) is repoussed in the well-known Swami style with images of various Indian demi-gods on the bowl."},
    {img: trade8.src, name: "Ganjifa cards", date: "Late 19th to early 20th century\nEngraving", popupimg: poptrade8.src, details: "This engraving of the Town Hall building, completed in 1830, is taken from a photograph by Firth & Co., a company specialising in photographic postcards, established in Reigate, Surrey. Designed in the neo-classical style of architecture, the Town Hall was built at the heart of the Bombay Fort. It is now known as the Asiatic Society of Mumbai and houses one of the largest libraries in the country."},
    {img: trade9.src, name: "Ivory artisans", date: "Late 19th to early 20th century\nClay models", popupimg: poptrade9.src, details: "The Museum has a unique collection of clay models that showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. The collection includes models of craftsmen practicing traditional crafts and occupations.\nThis is a model of artisans producing ivory products using traditional tools. Ivory articles were in great demand in the Western market during the colonial period. The chief centres for ivory production in the Indian subcontinent were Delhi in north India, Murshidabad in West Bengal, Mysore in South India and Moulmein in Burma. The Museum has a fine collection of ivory articles and figurines produced at these centres."},
    {img: trade10.src, name: "Jar, India", date: "Late 19th to early 20th century\nEnamel on silver", popupimg: poptrade10.src, details: "Enamelling is the art of ornamenting the surface of metal by fusing together different minerals over it to create designs in colour. The metal is first engraved, chased or repoussed to provide depressions within which the colours are embedded. The range of colour attainable on gold is greater than on silver and still more on copper than on brass. In India, Jaipur and Kashmir are two important centres of this art form."},
    {img: trade11.src, name: "Jug, Hyderabad", date: "Late 19th to early 20th century\nBidri", popupimg: poptrade11.src, details: "In the art of Bidri, pure silver is inlaid against a black background made of zinc and copper to create delicate decorative patterns on items of domestic use for wealthy patrons. The term 'Bidri' is derived from Bidar (Karnataka), the earliest centre of this art tradition in India. It was introduced from Persia in the 14th century where it was used to embellish weapons."},
    {img: trade12.src, name: "Kettle, Kutch", date: "Late 19th to early 20th century\nSilver", popupimg: poptrade12.src, details: "Decorative objects made of silver were in high demand in the European market. Different provinces in India produced silver objects, each with their own distinct styles. Kutch in Gujarat was famous for its graceful and intricate floral designs executed in shallow repousse as seen on this kettle. The spout of the kettle, in shape of an elephant’s trunk, and the small silver elephant on the lid also indicate the popularity of such Indian motifs in the West."},
    {img: trade13.src, name: "Lampstand, Ratnagiri", date: "Late 19th to early 20th century\nBison Horn", popupimg: poptrade13.src, details: "This elaborately carved Lamp stand made of Bison horn from the Ratnagiri School of Art is a combination of European form and Indian decorative embellishment like the cobra. Horn, was one of the few natural raw materials to be used for aesthetic as well as utility purposes in the 19th – 20th centuries.\nBuffalo and bison horn were primarily used in the production of decorative horn objects. The horn was shaped by moistening it with coconut oil and heating on a fire until it reached a soft wax-like state. It was then hand worked to its desired form or placed in moulds made of wood, polished and ornamented with designs. Ratnagiri and Sawantwadi in Maharashtra were important centres for the production of ornamental horn objects."},
    {img: trade14.src, name: "Parvati and Ganesh, Mumbai", date: "Late 19th to early 20th century\nSandalwood", popupimg: poptrade14.src, details: "Images of Hindu deities, such as this example from the Sir J.J. School of Art were popular themes represented on sandalwood objects. The preoccupation with Renaissance language in Indian art at this time is exemplified in the contrapposto figure of Parvati, the fall of her garment and her facial features.\nSouth India and Maharashtra were important centres for sandalwood carving in India."},
    {img: trade15.src, name: "Radha Krishna, Thiruvananthapuram", date: "Late 19th to early 20th century\nIvory", popupimg: poptrade15.src, details: "In response to growing European influence in India, Mysore and Trivandrum became primary centres of the ivory carving industry. The British attempt to encourage naturalism, or the realistic portrayal of nature, is evident in the dancing figure of Radha and Krishna.\nThe chief centres for the production of ivory articles in the Indian subcontinent were Delhi in north India, Murshidabad in West Bengal, Mysore in South India and Moulmein in Burma."},
    {img: trade16.src, name: "S.S. Siam, Mumbai", date: "1897 \nWood", popupimg: poptrade16.src, details: "This detailed wooden reproduction of the S.S. Siam is on display in the Industrial Arts Gallery. S.S. Siam was owned by the Peninsular & Oriental Steam Navigation Company, a British shipping company, and sailed between London and Australia via the Middle East and India. It was in the dry docks at Mazgaon for repairs when a young apprentice named Dayal Kanjee modelled a miniature version of it in 1897. The model has one big tunnel, two anchors, two main masts and two life boats. It was a gift to the Museum from E.J. Kail whose family were its original owners."},
    {img: trade17.src, name: "Shield", date: "Late 19th to early 20th century\nKoftagiri", popupimg: poptrade17.src, details: "This shield from Multan, with silver and gold wire inlay in a complex and intricate pattern, exemplifies the Museum's Koftagiri (Damascene) collection. The art of damascening decorative objects is alive in places such as Udaipur, Jaipur, Alwar and Sirohi in Rajasthan, Datia in Madhya Pradesh, Trivandrum and Bidar in the South and in Kashmir."},
    {img: trade18.src, name: "Ship", date: "Late 19th to early 20th century\nMother of Pearl", popupimg: poptrade18.src, details: "This model of a ship mounted on a stand, has sails made of mother-of-pearl and a small thimble holder. A miniature ship is also seen painted on it. In India, Ahmedabad, Surat and Khambat (Cambay) were the main centres for the production of decorative mother of pearl objects exclusively for export.\nMother of Pearl is the layer formed inside the shell of molluscs. The production of decorative objects in mother of pearl found patronage under Mughal rule in the Indian subcontinent. Growing trade between Europe and Asia from 16th century onwards made mother of pearl articles popular in the European market."},
    {img: trade19.src, name: "Silver craftsman", date: "Late 19th to early 20th century\nClay model", popupimg: poptrade19.src, details: "The Museum has a unique collection of clay models that showcases the people of Mumbai, their lifestyles and culture, in the late 19th and early 20th centuries. The collection includes models of craftsmen practicing traditional crafts and occupations. This is a model of a silver craftsman at work, with his tools including chisels, scorpers and gravers, shown around him. Silver was a preferred material for traditional craftsmen because of its malleability, ductility, fusibility and the ability to work its surface.\nKashmir, Burma, Pune, Chennai, Kutch and West Bengal were the principal centres for the production of silver objects in the Indian subcontinent."},
    {img: trade20.src, name: "Sind Lacware", date: "Late 19th to early 20th century\nLacquered wood", popupimg: poptrade20.src, details: "The Museum possesses one of the finest collections of 19th century lacware from Sind. The creation of coloured lac for application on wooden articles is a long and laborious process. Complicated techniques were used to produce a variety of designs such as Abri (Cloud work), Atisi (Fire work) and Nakshi (Pattern work)."},
]